### ISSUE TITLE
Launching an existing app now fails

### ISSUE THREAD

**Issue by gnyrd** [dmarmor/epichrome#85] opened 2016-10-14 12:53 UTC
The first attempt displays:

![untitled 8](https://cloud.githubusercontent.com/assets/2048411/19388010/bf12633a-91da-11e6-9d41-95dbeda04259.png)

followed by:

![untitled 6](https://cloud.githubusercontent.com/assets/2048411/19387896/3d5b09f0-91da-11e6-9fbe-f087827ee8eb.png)

followed by:

![untitled 9](https://cloud.githubusercontent.com/assets/2048411/19388025/ceae444e-91da-11e6-9587-d7aad95bdd62.png)

followed by:

![untitled 7](https://cloud.githubusercontent.com/assets/2048411/19387908/47d66d8e-91da-11e6-818c-2777f25b2070.png)

Second attempt to launch an epichrome app produces: 

![untitled 5](https://cloud.githubusercontent.com/assets/2048411/19387827/f6dbd82e-91d9-11e6-80cf-942504ed193e.png)

This occurs with every epichrome app I have created.

**Comment by dmarmor** [comment] 2016-10-14 18:15
Thanks for letting me know about this. The problem is your apps are still using an old version of the Epichrome engine, 2.1.11 or earlier. This problem has been fixed as of 2.1.12.

However, this has shown me a problem with the way Epichrome apps handle self-updating--they should be updating the engine first, and only then trying to update to a new version of Chrome. I'll fix that in the next update, though obviously that doesn't help with your existing apps.

For now, for existing apps, you have two options: you can install the latest Epichrome and recreate the apps, or you can do some minor surgery on them before running them again. I find the surgery to actually be easier, though both methods take a little care.

To do the surgery, you will need the latest Epichrome installed. In a terminal window, you'd do the following:

```bash
cp /Applications/Epichrome.app/Contents/Resources/Runtime/Resources/Scripts/strings.py <path-to-your-app>/Contents/Resources/Scripts
```

Say yes when it asks if you want to overwrite the file. When you run the app, it should now update properly.

If you prefer to recreate an app, use the ["simple method" in the README](https://github.com/dmarmor/epichrome#simple-method "simple method").

Please let me know how it goes! I'll close the issue for now, but if you're still having trouble we can reopen it. Thanks!

**Comment by ylluminate** [comment] 2016-10-14 18:24
THANK YOU!!!  The "surgery" method is super duper simple.  Fantastic.

**Comment by dmarmor** [comment] 2016-10-14 19:45
Reopening this issue for now so others can find it. A workaround to this problem is available in this comment: https://github.com/dmarmor/epichrome/issues/85#issuecomment-253880331

**Comment by wizonesolutions** [comment] 2016-10-24 19:30
Note: Workaround didn't work for me. Everything seems to have been wiped from the application directories. Seems I will have to recreate, though I can try the workaround on apps I've never tried to update yet.

**Comment by dmarmor** [comment] 2016-10-24 19:37
Yes, I should've specified--the workaround only works on apps that have not yet failed to update. Sorry about that.

Check the re-creation method in the Readme for the most painless way to do it. The TL;DR is, you need to completely delete the old app (like, using rm or making sure you empty the trash). Give it a minute for Spotlight to realize the app is gone. Then recreate in Epichrome using the _exact_ same name. Then Epichrome should give it the same ID, and when you run it, it will find your existing settings.

**Comment by wizonesolutions** [comment] 2016-10-25 11:56
That worked. I think I have rescued my apps now :) thanks

**Comment by kitsuyui** [comment] 2016-10-25 17:45
Thanks, I was rescued too!

And I made an one-liner shell command that execute this surgery command to all apps ;-)

```console
find /Applications ~/Applications | grep Scripts/strings.py | grep -v Epichrome.app | xargs -L 1 -I '{}' cp /Applications/Epichrome.app/Contents/Resources/Runtime/Resources/Scripts/strings.py {}
```

**Comment by dmarmor** [comment] 2016-11-01 21:25
Hi everyone. I've just released version [2.1.14](https://github.com/dmarmor/epichrome/releases/tag/v2.1.14). I'd highly recommend everyone update as soon as possible. Unfortunately, this will not be a totally simple process if you're running 2.1.13. Please see the note referenced in the release for the procedure. It's kind of similar to kisuyui's one-liner for allowing updating from pre-2.1.12 releases.

So sorry for all these update problems. I think (I hope!) I've fixed them all with 2.1.14 so we should be able to return to smooth automatic updating from here on out.

(Leaving this issue open for a while longer as people likely are still on older versions...)

**Comment by ylluminate** [comment] 2016-11-01 21:32
@dmarmor thanks for the update! Really do appreciate your work on this and the update notes to help us beat them all down in one whack. Can you suggest a quick one-liner to also back up all Epichrome apps before making the change?

**Comment by dmarmor** [comment] 2016-11-01 21:45
That's a great idea, @ylluminate! I think I'll actually try to throw together a little shell script that people can download that will create backup archives of all Epichrome apps, then run both @kitsuyui's and my one-liners to make them all ready for updating.

Will try to get to that quickly...

**Comment by dmarmor** [comment] 2016-11-01 23:55
Hey, I just updated the 2.1.14 release. The new DMG includes a script which will back up all your Epichrome apps and apply both the strings.py fix and a new fix needed so that 2.1.13 apps can be updated properly.

If you have a chance, please take a look and give it a try. Thanks!

**Comment by dmarmor** [comment] 2016-11-02 05:20
Just released 2.1.15 with a small fix to the updating code. In the sincere hope that epichrome_fix.sh will solve this updating problem for folks without them having to resort to searching through issues, I'm going to close this one. Please do let me know if anyone continues to have trouble with this. Thanks for all your help, everyone!

**Closed by dmarmor** 2016-11-02 05:20 UTC

**Comment by ylluminate** [comment] 2016-11-02 05:35
@dmarmor YOU ARE AWESOME.  THANK YOU!!! 🌞

**Comment by dmarmor** [comment] 2016-11-02 23:44
Thanks! So glad that's helping. I'm kind of embarrassed about all the breakage, but hopefully it's all patched up and things will be smoother from here on out...

**Comment by wizonesolutions** [comment] 2016-11-04 16:56
Wow, that script was slick! Things seem to be in order...

**Comment by dmarmor** [comment] 2016-11-04 18:42
Awesome! Glad it's working...
