### ISSUE TITLE
Chrome update destroyed apps?

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#40] opened 2015-12-04 06:09 UTC
Just restarted my system, fired up my Epichrome apps, was prompted that it was updating Chrome and now none of my Epichrome apps are starting.  Apparently this must be from an update that just happened within the last couple days.  Any ideas on how to get the apps working again as I feel lost without Epichrome now... :)

**Comment by breeden** [comment] 2015-12-04 18:25
Did you get your apps working again? Usually when Epichrome prompts that it is updating Chrome, I have to wait a minute or two for the update to take place, then restart the Epichrome app. If you restart the Epichrome app right away (before the update is finished), it will hang.

**Comment by ylluminate** [comment] 2015-12-04 18:51
Well not really.  I forgot that I was running BETA channel and the update that occurred was a BETA update that has apparently broken Epichrome.  I backed down to STABLE and it started up again.  Obviously we're heading pretty soon to some kind of a breaking change.  I was hoping to use BETA in order to get some advantages of speed on OS X.

**Comment by breeden** [comment] 2015-12-04 19:28
I wonder if this might be related to the issue #35 which came up a few weeks ago on the Chrome dev channel?

**Comment by rgbink** [comment] 2015-12-04 23:48
Confirmed breakage. None of my Epichrome apps are working, and I am running on the stable Chrome release. Also confirmed, after Epichrome app initiated update.

**Comment by breeden** [comment] 2015-12-04 23:57
Interesting! My apps are still working fine after an Epichrome-initiated Chrome update. Anyone getting helpful error messages off of the Console?

**Comment by ylluminate** [comment] 2015-12-04 23:58
@breeden I do believe that it is related to or the same as #35 as well.  In my case I was able to get STABLE working, but obviously for @rgbink he's seeing it happen for STABLE as well.

**Comment by breeden** [comment] 2015-12-05 00:02
Bummer! Per #31 it looks like @dmarmor is incommunicado for the time being, so unless anyone else has any better ideas we may need to sit tight for a few days...

**Comment by rgbink** [comment] 2015-12-05 00:16
Scratch that. `chrome://version/ ` revealed that I was in the beta channel. Don't recall when, but I obviously jumped into beta.

Reinstalled stable and all is well.

Fix (for now) is to revert to stable.

**Comment by evansthompson** [comment] 2016-01-07 21:44
This is related to #35.  On 12/3/15, Google [promoted Chrome 48 to the Beta channel](http://googlechromereleases.blogspot.com/2015/12/beta-channel-update.html). Build 48.0.2564.23 to be precise.  Here's the [basic changelog](https://chromium.googlesource.com/chromium/src/+log/47.0.2526.73..48.0.2564.23?n=10000) for that update. 

The build that first broke Epichrome as described in #35 is build 48.0.2560.0, released on 11/10/15. Here's its [basic changelog](https://chromium.googlesource.com/chromium/src/+log/48.0.2552.0..48.0.2560.0?n=10000). 

I tinkering around a little, following the steps in #31 and wonder if this Chromium issue [Issue 523045: Opt Google Chrome into stricter OS X Security Policies](https://code.google.com/p/chromium/issues/detail?id=523045) is related.

Following along on #31, I eventually got a Code Signing error. That lead me to [Unsign](https://github.com/steakknife/unsign). I then copied the Unsigned Google Chrome, and renamed it without the `.unsigned` extension.

It opens now, but it doesn't appear to be separated from the main Chrome.app running.

I'm guessing it's this change:

5246dc0 [Opt Google Chrome into the OS X "restrict" flag by kerrnel · 9 weeks ago](https://chromium.googlesource.com/chromium/src/+/5246dc07bd2d009d8865b213e74a09c9dd79180b)

No idea what to do or try next or how to resolve it. 

BTW, I'm assuming we're all on El Capitain.

**Comment by netnichols** [comment] 2016-01-21 13:41
Chrome 48 just became stable... guess there are going to be a lot of broken Epichrome apps. :-(

**Comment by dmarmor** [comment] 2016-01-22 04:50
Hi everyone, a fix is in the works for this. I'm closing this issue--check on issue #46 for updates. Sorry your apps aren't working right now, but should be fixed tonight. Thanks!

**Closed by dmarmor** 2016-01-22 04:50 UTC
