### ISSUE TITLE
Closing and window and clicking icon again doesn't open the SSB App mode

### ISSUE THREAD

**Issue by mholtrlc** [dmarmor/epichrome#29] opened 2015-09-28 22:31 UTC
Hi,

If I open up the app that I created and then close the window while leaving the app open, when I click the App Icon again it opens a regular Chome window with tabs in the App.  Is there any way around this?

**Comment by dmarmor** [comment] 2015-09-29 14:58
Hi @mholtrlc,

I don't think there's any way around that--it's just a feature of Chrome. The same thing happens if you close all the windows in Chrome itself and then try to re-launch it.

Just curious, is this something you do regularly? How would you want the app to act in that situation?

**Comment by omere2** [comment] 2015-10-04 12:06
@dmarmor 
Can it be set to launch the url on startup? I tend to close the windows all the time and the expected behavior is actually that the apps goes to background but doesn't really close. 
Fluid app allows for this behavior.

**Comment by dmarmor** [comment] 2015-10-17 23:55
Hi @omere2,

As I mentioned to @mholtrlc, the problem is that when you double-click the app and it's already open, it's not actually launching anything, and there's no way for me to know that that's what happened. I could potentially add some kind of hot-key that would tell the extension to kill all open windows and open the default, but that doesn't seem like an ideal solution anyway.

For now I'm going to close this issue, since I don't really have a fix for it. If you have ideas of how to get the behavior you're looking for, feel free to reopen or just post here. In the meantime, I'd suggest just quitting the app before you reopen it, and your default url will open as expected.

**Closed by dmarmor** 2015-10-17 23:55 UTC
