### ISSUE TITLE
Randomly losing custom icon

### ISSUE THREAD

**Issue by rschend** [dmarmor/epichrome#51] opened 2016-02-01 20:49 UTC
Love Epichrome. I've been waiting for it to come along for awhile. Nice work!

Every once in awhile, my epichrome SSBs lose their custom icons and I have to restart to get them back. I haven't identified the pattern yet, but it's definitely sometimes happening upon file downloads. But not always. Seems pretty random.

Pic:

![ssb no icon](https://cloud.githubusercontent.com/assets/10687740/12730674/ff7bda18-c8fa-11e5-8469-7bbd358a1db2.jpg)

**Comment by breeden** [comment] 2016-02-01 21:13
Interesting! Glad you have an effective workaround (and really, who doesn't need periodic restarts?). Sounds like @dmarmor isn't actively working on updates right now (as per his note in the last release), so maybe you can pay attention to the pattern and let us all here know when you've got a better idea what's causing the lost icons. If others can recreate the problem, maybe we can come up with fix.

**Comment by rschend** [comment] 2016-02-01 21:40
Understood. Will do my best. Would love for others to report if they're experiencing the same thing. Esp because I'm experiencing it on multiple machines.

thanks!

**Comment by zeartist** [comment] 2016-02-03 15:39
+1! 

I just tested, basically it happened when I downloaded a file in that SSB. I tried re-launching, which fixes it back, and then downloading and then BAM! ;-)

**Comment by kocolosk** [comment] 2016-02-05 00:25
Same here, icon disappears after the first file download. New behavior since upgrading to 2.1.9 to fix #50

**Comment by zsection** [comment] 2016-02-10 06:22
I'm getting this too regularly. I've updated to 2.1.9 but still experiencing the issue

**Comment by rschend** [comment] 2016-02-14 02:56
Probably because I hadn't recently download a file that's taken more than a few seconds to complete, it never occurred to me until now, that this must somehow be related to the Chrome download progress badge.

Right?

![dl badge](https://cloud.githubusercontent.com/assets/10687740/13031451/7b2667c8-d29c-11e5-830b-db8518fdb4a3.jpg)

**Comment by dmarmor** [comment] 2016-02-15 02:32
Hey @rschend and everyone else who's reported this, sorry for the slow response--I think I finally have a fix for this in the latest release. Please update to this release and update all your SSBs as soon as possible, as it also fixes a potentially much more serious bug related to Chrome's auto-update code.

Thanks for the reports and sleuth-work, and please keep me posted with any more problems related to this.

**Closed by dmarmor** 2016-02-15 02:32 UTC

**Comment by kocolosk** [comment] 2016-03-22 19:14
Confirmed fixed for me in 2.1.11. Thanks!
