### ISSUE TITLE
Notifications show Chrome icon, not app's custom icons, clicking on Notification often brings wrong app to front first.

### ISSUE THREAD

**Issue by dsemaya** [dmarmor/epichrome#128] opened 2017-08-25 22:01 UTC
I have set up Epichrome apps for Gmail, Hangouts, etc.  However when a notification appears it shows the Chrome icon, not the icon of the Epichrome app.  

Also, when clicking on notifications, often the wrong Epichrome app is brought to the foreground first.  

Is there a way to configure Epichrome so that it makes a unique copy of the Chrome engine, with it's own bundle identifier?  If so, would that allow each app to have its own unique notifications.  I previously [filed a bug](https://github.com/dmarmor/epichrome/issues/108) that each Epichrome app shares its notification settings with Chrome, which is undesirable.  

Thanks.

**Comment by dsemaya** [comment] 2018-01-29 18:30
Any thoughts on a way to solve this?  I'd be content with figuring out how to change just the icon.

**Comment by jameschao** [comment] 2018-09-30 23:16
This seems to be a duplicate of https://github.com/dmarmor/epichrome/issues/122.

**Comment by talleux** [comment] 2019-03-16 22:01
Well, this issue actually contains two issues, in my opinion:
1) Notifications show Chrome icon, not app's custom icons --> this looks duplicate with #122
2) Clicking on notification often brings wrong app to front first (for me it's different: clicking on it will open the link in ALL currently open Epichrome instances AND GoogleChrome (if opened), which makes notification unusable)

**Comment by dmarmor** [comment] 2019-03-19 23:53
Closing this issue and moving the discussion to #122...

**Closed by dmarmor** 2019-03-19 23:53 UTC
