### ISSUE TITLE
Custom icons not showing up in application switcher

### ISSUE THREAD

**Issue by empathetics** [dmarmor/epichrome#252] opened 2020-06-08 14:58 UTC
Custom icons are present in the dock, but not in application switcher (which is really where they're relevant for me for at a glace app switching without reading). These are ones not set during app creation, but after using app info settings.

**Comment by talleux** [comment] 2020-06-08 15:06
Hi @empathetics 
Some infos from #226 and #232 should help you workaround your problem.
You probably have the apps from /Applications linked in your Dock but the Apps are actually run from /Applications/Epichrome/EpichromeEngines.noindex/[Macos-USER]/[AppName]

**Comment by dmarmor** [comment] 2020-06-08 23:07
Thanks, @talleux , this is exactly right. Custom icons added after the fact will never work as smoothly as ones set during app creation, and will definitely get lost when the engine is recreated for any reason (as during an update). App editing is coming, hopefully relatively soon, at which point you'll be able to attach your custom icons more permanently.

Closing this issue for now.
Duplicate of #226

**Closed by dmarmor** 2020-06-08 23:07 UTC
