### ISSUE TITLE
Version 2.4.5 app aborted with error: "Error launching engine: Timed out waiting for "Habitica Chrome.app" to open. The app may not have launched properly. If it did, the engine will not be properly cleaned up upon quitting." [main(678)]

### ISSUE THREAD

**Issue by icotext** [dmarmor/epichrome#333] opened 2021-05-03 21:56 UTC
```
*[7591]HabiticaC540(547)/launchapp(2887): Error launching engine: Timed out waiting for "Habitica Chrome.app" to open.
2[7591]HabiticaC540(632)/launchurls(2971){Google Chrome}:
2	2021-05-03 14:56:15.092 Google Chrome[10219:50275] Error loading /Library/CoreMediaIO/Plug-Ins/DAL/mmhmmCamera.plugin/Contents/MacOS/mmhmmCamera:  dlopen(/Library/CoreMediaIO/Plug-Ins/DAL/mmhmmCamera.plugin/Contents/MacOS/mmhmmCamera, 262): no suitable image found.  Did find:
2		/Library/CoreMediaIO/Plug-Ins/DAL/mmhmmCamera.plugin/Contents/MacOS/mmhmmCamera: code signature in (/Library/CoreMediaIO/Plug-Ins/DAL/mmhmmCamera.plugin/Contents/MacOS/mmhmmCamera) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
2		/Library/CoreMediaIO/Plug-Ins/DAL/mmhmmCamera.plugin/Contents/MacOS/mmhmmCamera: stat() failed with errno=9
![7591]HabiticaC540(678)/abortreport(1155)/abort(1093): Aborting: Error launching engine: Timed out waiting for "Habitica Chrome.app" to open. The app may not have launched properly. If it did, the engine will not be properly cleaned up upon quitting.

```

**Comment by dmarmor** [comment] 2021-05-03 23:45
Duplicate of #332 

Moving discussion to that issue.

**Closed by dmarmor** 2021-05-03 23:45 UTC
