### ISSUE TITLE
Losing icon, losing app name

### ISSUE THREAD

**Issue by daviddumonde** [dmarmor/epichrome#173] opened 2018-10-29 23:23 UTC
The apps I create with Epichrome have been intermittently either losing the custom icon, or losing the app name.

So a few minutes ago I noticed my "tulane.app" no longer showed the Tulane logo on the Mac app switcher, and instead showed the Chrome icon.

Then I quit and relaunched "tulane.app" and now the Tulane logo is back on the Mac app switcher, but the app name in the menubar has reverted to Chrome (not "Tulane").

I'm not aware of doing anything specific to update Epichrome or Chrome or my "tulane.app", so I have no idea what's causing this.

Thoughts?

**Comment by grigorye** [comment] 2018-11-02 15:06
I wonder if it's due to update of Chrome.

I have a few SSBs that suffer from this, but one that doesn't. And the only relevant difference that I see there is that SSB.app/Contents/Resources/ChromeEngine/SSB.app/Contents/Resources/xx.lproj/InfoPlist.strings have "(Google) Chrome" for CFBundleName/CFBundleDisplayName. And CFBundleGetInfoString for the "bad" SSBs is set to "Google Chrome 70.0.3538.77..." while for the "correct" one it is set to "Google Chrome 69.0.3497.100...".

**Comment by relluf** [comment] 2019-01-05 04:53
Does anybody have any pointers to in which part of the code could reside a bug causing this issue?

**Comment by onching** [comment] 2019-01-28 19:32
oh. I also recreated the SSB app from scratch hoping that it would fix the issue. it seem to work fine after a few application open and closes but a few days later it happened again. maybe sleep/restore or something?

**Comment by sahi1l** [comment] 2019-02-05 18:52
Issue #51 covered the same issue (with the icon), and they determined that it occurred when the browser downloaded a file. The issue was supposedly resolved, but I have been noticing the same problem recently and I have confirmed that downloading a file caused the icon to be replaced by the generic version.

**Comment by Penworks** [comment] 2019-02-20 13:42
hi. Im just testing this out (10.10.5) 
<img width="43" alt="screen shot 2019-02-20 at 14 42 08" src="https://user-images.githubusercontent.com/758626/53095667-b942d780-351d-11e9-9611-fa4abb00fabd.png">
and cannot get it to take custom icons - they appear as a generic rectangle with a pen and pencil crossed in the right corner (see screengrab). Other than that this seems great.

**Comment by dmarmor** [comment] 2019-02-27 01:25
Hi all, I've just done a beta update, mainly to address some even worse issues with routing links to the default browser (see issues #163, #167 & #169). But it appears on my system to solve this issue as well. I'd appreciate if folks experiencing this could try the beta and let me know if it helps. Thanks!

[epichrome-2.2.4b01.dmg.zip](https://github.com/dmarmor/epichrome/files/2908136/epichrome-2.2.4b01.dmg.zip)

**Comment by dmarmor** [comment] 2019-03-12 00:14
Have any users with this issue experienced improvement (or not) with 2.2.4b01? On my system, it seems to have solved the problem on Mojave 10.14.3. I'm planning to release 2.2.4 official tonight, and would love to know if this issue has been resolved for more than just me...

**Comment by dmarmor** [comment] 2019-03-13 16:10
Thanks for the update. Let's check in on this after the next Chrome update and see if it stays solved.

**Comment by talleux** [comment] 2019-03-16 22:30
I still have the problem, that the icon changes to the generic one when downloading a file, *on some of my instances* only. I saw in some other issue that instances created with older versions of Epichrome could be affected, but i can't confirm this: for example my GoogleDrive-Instance is one of my very first one and maybe 2 years old and it doesn't have that problem whereas some other newer instances do have the problem.
I use Epichrome 2.2.4 on Mojave 10.14.3

I read i that other issue some ideas for fixing those instances (reboot, move the app away from the Application folder and back) but it doesn't help for me.

**Comment by gregschroeder** [comment] 2019-05-05 16:08
+1

I can't figure out the cause, but it happens a lot to me. I lose the icon, and often also the app name in the menu bar. 

I end up keeping a good copy of each SSB .app folder elsewhere, and when this happens, I restore (clobber) the active one with the backup copy and it works fine again.  (just the .app folder, nothing from Application Support or other preference folders)

**Comment by gregschroeder** [comment] 2019-05-08 15:42
I haven't had a chance to pursue this at all, so it may be a red herring, but I'm wondering if this has something to do with using Chrome Sync.   The reason I mention this is that I created a few SSBs via Epichrome that all logged in to the same Google account in order to sync Chrome settings.  I noticed that when one of those loses its appname and icon, they all seem to.

**Comment by onching** [comment] 2019-05-08 16:32
I have the same set up where 4 SSB use the same google account to sync but for me they don’t lose the icon at the same time. Do you start all the SSBs at the same time? I don’t. Also lately it seems like the SSB that is used for gmail loses its icon a lot sooner or more frequent that the others. On 2.2.4 and Mojave

**Comment by heyfletch** [comment] 2019-05-19 12:46
+1 I have all the issues and circumstances described in this thread. Only thing to add: this issue (icon and app name disappearing) occurs on my Macbook, but not my iMac.

**Comment by talleux** [comment] 2019-06-13 07:18
> I haven't had a chance to pursue this at all, so it may be a red herring, but I'm wondering if this has something to do with using Chrome Sync. The reason I mention this is that I created a few SSBs via Epichrome that all logged in to the same Google account in order to sync Chrome settings. I noticed that when one of those loses its appname and icon, they all seem to.

I don't use Google Sync / i don't login in any of my SSB so for me it hasn't to do with this.

**Comment by talleux** [comment] 2019-08-14 07:44
Hello @dmarmor are you still waiting for infos? How could i help with more infos?

**Comment by dmarmor** [comment] 2019-09-21 00:01
Hi all, sorry for disappearing for so long. I've been utterly unable to recreate this on my system. Since 2.2.4, my app icons have been rock solid. Assuming you have confirmed that all your apps have been properly updated to 2.2.4, I wonder if you could let me know if this problem is occurring only with apps that you created before 2.2.4 and then updated, or if it also occurs with new apps you created using 2.2.4?

**Comment by heyfletch** [comment] 2019-09-24 20:26
I still have the same issues described above. HOWEVER, good chance my apps were created before 2.2.4. 

How do I tell which version of Epichrome I'm using? Is that just on the Epichrome.app or across the apps I created? 

Is there an easy way to see which apps I created with Epichrome? (I may try deleting them all and starting fresh... thought I did that already, but may have missed some)

I am using Epichrome Helper extension v1.1.2.

**Comment by dmarmor** [comment] 2019-10-01 16:52
Hi @heyfletch,

The version of Epichrome will appear not only in the Finder info for Epichrome itself, but for each app.

If you confirm that the apps you're having problems with have updated themselves to 2.2.4, then the next thing to try would be to take one of them, ensure it's not running, back it up, and then go into the app bundle and delete the Payload directory. The next time you run, it should recreate it. I once ran into a situation where the Payload directory had become corrupted. I'm still not sure why it happened, and it's never happened again, but it could be worth a shot. Please let me know if it helps!

As for seeing a list of all your Epichrome apps, teh best way I know to do this is in the terminal with mdfind:

```bash
mdfind "kMDItemCFBundleIdentifier == 'org.epichrome.app.*'"
```

(This will also list a bunch of Chrome apps in your Epichrome profiles, but it should list the actual apps first.)

**Comment by heyfletch** [comment] 2019-10-07 15:57
Confirming all apps were 2.2.4. At least one of them one was created in Oct 2018. I've now deleted the payload for all 3 apps. So far, no issue, but it was always intermittent, so I'll report back here if any further issues. Thanks for the mdfind and Finder info tips!

**Comment by onching** [comment] 2019-10-16 02:22
I also still experiencing the wrong icon (in dock) / epichome app name (top left name usually says the epichrome app name instead of chrome) but I just tried the delete payload steps mentioned above. I'll report back if I see it happening again. It does seem to be intermittent for me as well. I put my laptop to sleep a lot instead of closing apps, I'm not sure if that has any correlation though. Thanks!

**Comment by relluf** [comment] 2019-10-30 15:30
My problems around icons and app names have practically disappeared, but, activating the app through Spotlight or the Finder is still really instable. I use an app called Apptivate to switch between apps by hotkeys and it oftentimes fails to activate the app. Activating an app through Spotlight and/or Finder shows the exact same behaviour. It is not consistent, not just one specific Epichrome'd app, sometimes it works and sometimes it just keeps failing, restarting the app might help, but then another might fail. It's seems to be totally random, I haven't noticed a pattern. 

When it fails, instead of activating the app, the app launches again. Its icon appears again in the Dock but then usually immediately quits. When I try to activate the app multiple times in a row (in frustration ;-)) the second icon will keep on bouncing a while in the Dock and then calm down, but it stays in the Dock. I can't remove it and clicking it doesn't activate anything. Rebooting is the only option I found to get rid of it (logging in again doesn't help either).

**Comment by onching** [comment] 2019-11-05 00:56
reporting back... I haven't noticed any icon issues since deleting the payload steps 20 days ago so that might have corrected my issue. I'm still on Mojave btw.

**Comment by relluf** [comment] 2019-11-07 07:00
@heyfletch FYI I managed to get my shortcuts working with FastScripts

**Comment by heyfletch** [comment] 2019-11-07 12:33
Thanks for the tip! Looks cool. :)

**Comment by relluf** [comment] 2019-11-07 15:19
> @heyfletch FYI I managed to get my shortcuts working with FastScripts

It might be useful to comment here that I noticed that using AppleScript to activate the app from the Terminal *does work*. For example the following activates or launches an app called Redmine:

`$  osascript -e "tell application \"System Events\" to activate application \"Redmine\""

The thing is, it's pretty slow to execute, on my system anyways (MBP15/2017) and that's how I came across this FastScripts-thingy. 

@dmarmor does this make ring any bells for you? Does the code in Epichrome do something similar? Is there a way I could debug it?

**Comment by talleux** [comment] 2019-11-08 20:29
Hello @dmarmor,

sorry for my late very answer to your earlier questions to me (https://github.com/dmarmor/epichrome/issues/173#issuecomment-533747962)...
As is said earlier (https://github.com/dmarmor/epichrome/issues/173#issuecomment-473597939) i have the problem of loosing the SSB icon when downloading a file on some of my SBBs. I really can't find a pattern: some very old SBBs don't have the problem, and some of the one i created recently have the problem, other not. I admit i didn't compare config files as i don't really know on what to focus when doing so. If you can give some tips on what files i could compare, i'd do it.
I did some tests with icon image files to check if this could be a reason but i don't think so.

I can reproduce the problem and it occurs always with the same SBBs.

If i can do something to help to find out what ist the differences between the SBBs with and without the problem, please tell me.

**Comment by dmarmor** [comment] 2019-12-02 22:01
Hi all,

I wanted to let you know I'm working on a major update that I believe will solve this, as well as many other long-standing problems. With my work schedule, it may take a while, but I'll let you know when it's ready for testing. Thanks for your patience!

One more thing:

#### <shameless_plug>
#### I've set up a [Patreon](https://www.patreon.com/epichrome). If you find Epichrome useful and would like to help support its continued development, I've love it if you considered joining. Your membership would help cover the costs and time I put into the project. Membership is per-release, so you'd only be charged when I put out a new version with significant work in it (e.g., assuming I end up with the bundled-Chromium architecture, I would not consider bumping the Chromium build to be a new version).
#### </shameless_plug>

**Comment by dmarmor** [comment] 2020-05-13 00:32
Hi all! I believe this issue should be solved in 2.3.0, so I'll close it for now. If you notice this problem in the latest update, please let me know and I'll reopen.

**Closed by dmarmor** 2020-05-13 00:32 UTC
Labels: pending

**Comment by daviddumonde** [comment] 2020-06-14 15:31
@dmarmor I appreciate your hard work on Epichrome, but Brave has been nothing but a headache for me for a variety of reasons, such as it won’t complete downloads. I’m giving up on Epichrome.

**Comment by dmarmor** [comment] 2020-06-15 21:38
Hi @daviddumonde I'm really sorry to hear that. I've appreciated your involvement on GitHub over the years. Out of curiosity, have you also been having problems with Chrome-based apps since 2.3.0?

**Comment by daviddumonde** [comment] 2020-06-16 12:32
No, haven’t had any issues until I downloaded the Brave version last week. Existing Chrome-based apps have been performing fine, even keeping their icons.

I’d file bug reports on the Brave version and try to identify some of the issues, but I’m just in a really busy period right now and can’t spare the time.

**Comment by dmarmor** [comment] 2020-06-16 21:41
I understand if you don't have time to file bug reports. The latest version of Epichrome does still allow you to create apps that use the Chrome engine (by choosing "External (Google Chrome)" on step 7), so maybe that can work for you where the Brave engine doesn't? But if not, then of course I understand if you need to find a different solution.

**Comment by daviddumonde** [comment] 2020-06-16 23:26
I didn’t realize I could run it on Chrome. I’ll give that a shot. Thanks for your help as always, David!

**Comment by dmarmor** [comment] 2020-06-16 23:42
No worries at all! I hope that helps, but if not (and if you have time), let me know how it goes and I'll do my best to fix any problems...
