### ISSUE TITLE
problems with macOS 11 beta

### ISSUE THREAD

**Issue by iamlayer8** [dmarmor/epichrome#275] opened 2020-09-25 18:39 UTC
When I try to create a new Epichrome app in macOS 11's current public beta, I get this error message:
> The app may not have launched properly. If it did, the engine will not be properly cleaned up upon quitting.

Also, updating existing apps to the new version of Epichrome fails. When I open an updated app, I get the error message 
> The app may not have launched properly. If it did, the engine will not be properly cleaned up upon quitting.

- macOS BigSur Version 11.0 Beta (20A5374i)
- Epichrome 2.30.12

**Comment by iamlayer8** [comment] 2020-09-26 08:54
OK, tested this on a different computer.
- creating a new app worked -> looks like a problem with the Epichrome install on the other machine.
- updating an existing app did not work. Error message when Updating was:
> Update succeeded, butUpdate succeeded, but the updated app didn't launch. (Epichrome helper app failed to launch.)

Versions:
- Epichrome 2.30.12
- macOS BigSur Version 11.0 Beta (20A5374i)

**Comment by boywithk9** [comment] 2020-09-29 14:53
I get the same error on MacOS 11 beta. I tried deleting and recreating the app, which worked at first. But now I'm getting the error again. I'm not getting it (yet) for a different instance.

**Comment by boywithk9** [comment] 2020-09-30 15:36
Also, when I do try and launch the app, it brings forward a different Epichrome app that doesn't produce the same error when launched.

**Comment by dmarmor** [comment] 2020-10-13 19:26
Thanks for these reports @iamlayer8 & @boywithk9. I believe this problem is related to a problem that I've fixed for the upcoming 2.4.0 release. I have set up a Big Sur beta boot drive and will test it before the release to make sure. Stay tuned...

**Comment by boywithk9** [comment] 2020-11-11 08:10
Big Sur is going to be released tomorrow. Any news on this?

**Comment by dmarmor** [comment] 2020-11-12 01:44
I've been doing tests with my Big Sur installation. I actually haven't experienced the problems you're having with 2.3.x apps, so it seems to at least work some of the time. That said, I haven't tested 2.3.x extensively as I'm focused on 2.4.0 right now. I'm trying to track down one problem with that version on Big Sur, but once I fix that, it hopefully should be ready to release it in a week or two. Thanks!

**Comment by zenopopovici** [comment] 2020-11-13 15:26
Multiple apps can't be started at the same time...

**Comment by dmarmor** [comment] 2020-11-14 00:00
Hi @zenopopovici, I need a bit more info on this. Which version are you using? This looks like one of the 2.3 versions, and as discussed above they can have some problems launching on Big Sur, so it may be solved in 2.4.0.

If I'm understanding correctly, you launch app A, then try to launch app B but app B doesn't launch. If you quit both, then launch app B first, does that one launch correctly and trying to launch app A fails the same way as app B had before?

Thanks!

**Comment by jaredkoon** [comment] 2020-11-14 00:53
@dmarmor - That is what I am seeing.

Using 2.3.17, with Big Sur installed, you can run any one of your Epichrome Apps (using the Brave Engine on mine, so not sure if this happens on Chrome as well), but when you attempt run the second one, it will instead switch back to the already running Epichrome app and then pop a "Unable to Run" warning message window.

See:

![Screen Shot 2020-11-13 at 7 49 45 PM](https://user-images.githubusercontent.com/13224584/99133849-91e14780-25e9-11eb-899e-e69ecd8301b7.png)

**Comment by dmarmor** [comment] 2020-11-15 17:28
So 2.3.x apps are going to have problems on Big Sur, as I'm only doing engine updates on 2.3 now. 2.4 is very near release, and I'm currently ironing out some last problems to make sure it will work smoothly on Big Sur. Anybody on Big Sur will want to update to 2.4 as soon as it's released...

**Comment by zenopopovici** [comment] 2020-11-15 19:13
Thank you @dmarmor for all your hard work. We have to be patient.

**Comment by jaredkoon** [comment] 2020-11-16 17:13
@dmarmor - Sounds good.  Thank you for the development and support of epichrome.  :)

**Comment by bendehghan** [comment] 2020-11-25 05:10
Any update on this please? When is 2.4 coming? I'd rather have a buggy version of 2.4 than to not have anything now that I'm already on macOS11.
Thank you

**Comment by dmarmor** [comment] 2020-12-02 01:32
Sorry it's been a slow process. I have very little time to devote to Epichrome and am moving as fast as I can with 2.4, but cannot release it until it's been properly tested.

(If you are in a position to support the project as a [Patreon patron](https://www.patreon.com/bePatron?u=27108162), I'd be grateful for both the financial and beta testing support! 🙂)

**Comment by asmusz-adobe** [comment] 2020-12-02 03:57
Thanks for all your hard work!   I'm sure you get lots of complaints here but want to say how much I appreciate all the work you do on this tool.  It's been a big help in my work productivity!

**Comment by jeffpoulton** [comment] 2020-12-02 15:04
Thanks for keeping us updated, dmarmor! Echoing @asmusz-adobe, Epichrome has been a core part of my productivity for years. Will gladly be a patron. Cheers...

**Comment by dmarmor** [comment] 2020-12-08 16:47
Hi all, I think I managed to find a simple fix to this issue, so I've just released 2.3.20. If you're still using 2.3 apps on Big Sur, would you please update them, see if this fixes the problem for you, and let me know here, either way?

Thanks!

**Comment by zenopopovici** [comment] 2020-12-08 17:10
@dmarmor Works! Brilliant, thanks!

**Comment by boywithk9** [comment] 2020-12-08 21:15
Yes, it’s fixed.

**Comment by iainad** [comment] 2020-12-09 12:54
@dmarmor Thanks so much for fixing this! Confirmed working on BigSur here.

**Comment by dmarmor** [comment] 2020-12-09 21:12
Looks like it's working for folks, so I'll close this for now. If the problem recurs, please let me know in the comments and I'll reopen. Thanks!

**Closed by dmarmor** 2020-12-09 21:12 UTC
