### ISSUE TITLE
Epichrome Broken w/ new version of Chrome (54.0.2840.59)

### ISSUE THREAD

**Issue by chrisvensko** [dmarmor/epichrome#86] opened 2016-10-14 19:28 UTC
Getting this error when trying to launch an existing or create a new Epichrome app:

```
Creation failed: Error filtering InfoPlist.strings (Traceback (most recent call last):
  File "/Applications/JIRA.app.23281/Contents.28250/Resources/Scripts/strings.py", line 52, in <module>
    print sys.exc_info()[1][1]
IndexError: tuple index out of range)
```

When launching an existing app it tells me that there is an updated Chrome, and then displays the error message above and the folder in finder is empty.

When creating a new app, after walking through the several input options and then trying to create the app, the error message above is displayed and there is no folder created.

Looking at my Chrome settings I'm currently at Chrome Version 54.0.2840.59 (64-bit).

**Comment by dmarmor** [comment] 2016-10-14 19:42
Duplicate of issue #85. Please see the last comment in that issue for a workaround.

**Closed by dmarmor** 2016-10-14 19:42 UTC

**Comment by wflanagan** [comment] 2017-03-21 13:29
FYI.. New apps will be deleted. You have to go back into the trash and put the app back to perform this fix.
