### ISSUE TITLE
Chrome Beta Version 54.0.2840.16 beta (64-bit) breaks Epichrome

### ISSUE THREAD

**Issue by GrogHills** [dmarmor/epichrome#80] opened 2016-09-12 06:02 UTC
With Chrome Beta Version 54.0.2840.16 beta (64-bit) Epichrome beta is broken. All my epichrome apps broke on the last update, and now when I run Epichrome to create a SSB I get the same error.

Creation failed: Error filtering InfoPlist.strings (Traceback (most recent call last):
  File "/Users/gmorse/Downloads/TEst.app.14774/Contents.2479/Resources/Scripts/strings.py", line 52, in <module>
    print sys.exc_info()[1][1]
IndexError: tuple index out of range)

This issue has occurred on two separate Macs when I updated to the latest Chrome Beta.

I just switched back to Google Chrome stable, i.e. non-beta release and Epichrome works great again. 

Unfortunately, during this process all my Epichrome SSB apps configs were destroyed and I have to re-create them.

Also, please note that I reviewed your suggestion on the home page to delete those two folders, then reinstall chrome, with no luck.

Can you help? Thanks!

**Comment by TheCorp** [comment] 2016-09-12 18:30
++ Same here

**Comment by kjwierenga** [comment] 2016-09-13 10:55
Duplicate of #77

**Comment by dmarmor** [comment] 2016-09-18 21:25
Hey guys, this will be fixed in the next release.

Epichrome doesn't seem to work with beta versions of Chrome (as you've discovered). I don't really have a good fixe for this if you need to be on Chrome's beta channel. So far it seems to work fine with all release versions once they come out.

**Closed by dmarmor** 2016-09-18 21:25 UTC
