### ISSUE TITLE
unable to open - when other epichrome open - with Brave engine

### ISSUE THREAD

**Issue by asmusz-adobe** [dmarmor/epichrome#285] opened 2020-11-30 17:30 UTC
For me, I use this setup with Browser Fairy to open links for specific things, each in it's own SSB.

1. Created app epi-salesforce using brave.
2. Created another for different site.
3. open epi-salesforce app - make sure it works properly
4. create rule in Browser Fairy for 1st epi-salesforce app
5. click related link on outlook - opens fine as expected
6. while that one is open double click 2nd app - page tries to load in epi-salesforce app and get:
"The app may not have launched properly. If it did, the engine will not be properly cleaned up upon quitting."

![error1](https://user-images.githubusercontent.com/65310062/100642166-49b26c80-32ed-11eb-998a-451fd44dea25.png)
[epichrome_app_log_20201130_091929.txt](https://github.com/dmarmor/epichrome/files/5617510/epichrome_app_log_20201130_091929.txt)

Please let me know what other logs I can provide.

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	429.50.1.0.0
  SMC Version (system):	2.45f4

**Comment by dmarmor** [comment] 2020-12-02 01:36
Duplicate of #275

**Closed** 2020-12-08 16:46 UTC
