### ISSUE TITLE
Unable to Run

### ISSUE THREAD

**Issue by hr2334** [dmarmor/epichrome#284] opened 2020-11-25 01:55 UTC
A long time epichrome user who just updated mac os to bigsur.  Had to recreate the applications.  I use brave browser and on my second epichrome app, get this error:

<img width="423" alt="Screen Shot 2020-11-24 at 8 54 27 PM" src="https://user-images.githubusercontent.com/66319308/100172857-3f304700-2e97-11eb-8dcd-246213b46fcc.png">

The Log states:

*[5615]Calendar(568)/setwelcomepage(696)/getextensioninfo(1404): Unable to get locale en name for extension nckgahadagoaajjgafhacjanaoiihapd. Using ID as name.
*[5615]Calendar(739)/clearmasterprefs(2481): Timed out waiting for app prefs to appear.
![5615]Calendar(860)/abort(884): Aborting: The app may not have launched properly. If it did, the engine will not be properly cleaned up upon quitting.

I've tried deleted and created it many with different names, no icon, but same error.  The application is for Google Calendar with url: https://calendar.google.com/calendar/u/0/r 

Thank you

**Comment by dmarmor** [comment] 2020-12-02 01:26
Duplicate of #275

**Closed by dmarmor** 2020-12-02 01:26 UTC
