### ISSUE TITLE
Getting a new error "Creation failed: Error filtering Info.plist file. (ascii)"

### ISSUE THREAD

**Issue by jonathanbranam** [dmarmor/epichrome#233] opened 2020-05-28 15:57 UTC
This morning I noticed that my Epichrome apps wouldn't launch. So, I restarted and then discovered an update to Epichrome, which I installed. I tried to launch an existing app and got this error. Then I tried to create a new app and got this same error.

Running Mojave: 10.14.6 (18G5033)

Thanks! I love Epichrome. As a developer I appreciate having browsers with different cookies and cache for logging into different environments or the same app with different credentials at the same time and organizing my webapps into nice browsers I can tab between.

**Comment by dmarmor** [comment] 2020-05-29 00:26
Thanks for checking in, and thank you for the kind thoughts about Epichrome!

This problem is discussed in issue #228, and at the end of the discussion you'll find a link to a new beta I posted yesterday to try to address it. It should show you the update dialog that hasn't been showing up on your broken apps. Please give it a try and post on issue #228 to let me know how it goes!

**Comment by dmarmor** [comment] 2020-05-29 00:27
Duplicate of #228

**Closed by dmarmor** 2020-05-29 00:26 UTC

**Comment by jonathanbranam** [comment] 2020-06-05 18:12
Thanks, everything worked great after the update!

**Comment by dmarmor** [comment] 2020-06-05 23:47
Excellent! Glad to hear it.
