### ISSUE TITLE
How to open .gdoc and other Google Docs files with Epichrome?

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#42] opened 2015-12-06 02:03 UTC
Right now Google Drive essentially forces .gdoc, etc. files to open with the default browser.  Is there a way to "teach" Epichrome browsers to open .gdoc and other Google Docs files?

I have assigned my Epichrome app to open .gdoc files, but it simply will not open them or appear to do anything once the file triggers Epichrome.  It's almost as if there needs to be some other function within Epichrome's Chrome instance itself to grok what to do with a .gdoc, etc. file.

**Comment by dmarmor** [comment] 2016-01-22 05:10
Sorry for the slow reply to this. So I understand, you have .gdoc files on your Mac and when you double-click them you want them to open in your Epichrome Google Drive app?

I don't personally have the Google Drive extension on my computer so I'm not sure--if you double-click them without configuring them to open in your Epichrome app, they would launch properly in Chrome? If that's the case, I'm not sure why they're not working. Epichrome apps are just wrappers around Chrome, so any behavior that happens in Chrome should happen in your app too.

Let me know if I'm understanding you correctly, and I'll add this to my to-do list. (A heads-up, though--my day job has just gotten very very busy, and I'm not likely to have time to add new features to Epichrome anytime soon.)

**Comment by dmarmor** [comment] 2016-02-15 02:04
Closing for now. @ylluminate, if you can give me a bit more info on the problem and desired solution, I'll reopen. Thanks!

**Closed by dmarmor** 2016-02-15 02:04 UTC

**Comment by ylluminate** [comment] 2016-02-15 02:41
Sorry, missed your reply here until your last one today.  So in order to interpret .gdoc files, it apparently has to pass through Google Drive.  They appear to be simply a JSON file that is then parsed by Google Docs app and then shunted on into the default browser.  I want my default browser to be Safari, but I want to open Google Docs files in an Epichrome dedicated app.  This presently isn't possible and I'm not really seeing a way around it...

**Comment by dmarmor** [comment] 2016-02-15 06:16
Gotcha. So if I'm understanding how it works, I think your best bet might be something I use called Browser Fairy. It's $5 on the Apple app store. Pretty bare bones, but you set it to be your default browser and then you can set up rules for routing links. I use it to route links to my various Epichrome SSBs and then my default fallback is Chrome, so for most situations it just acts like Chrome is my default browser.

It seems like this might work for you, since Google Drive sends links to your default browser, so if you can figure out a rule for how those links look, you should be able to tell Browser Fairy to route them to your SSB. You just need to make sure when you created the SSB in Epichrome you told it to "Register app as a browser." If not, you'll need to re-create it.

Let me know if you have more questions about that, and if you do give it a try, keep me posted if it works for you...

**Comment by ylluminate** [comment] 2016-02-15 06:50
What an excellent suggestion.  Thanks so much for that as I think it will be a perfect solution.  Re: recreating the SSB, I have customized this particular instance to the hilt and would much rather not recreate it.  Can I manually register this SSB in another way?  I'm assuming that I can execute some incantation from the shell or, at the very least, copy preferences and extensions over so as to minimize the headache of reconfiguring it...

**Comment by dmarmor** [comment] 2016-02-15 16:48
There's no simple way to edit an SSB to register it as a browser, as it would involve changing the Info.plist file. Probably your best bet would be to follow the instructions in the README for recreating it while preserving your settings. That way when you run the new SSB it should restore all your extensions and preferences.

The safest option would be to go into ~/Library/Application Support/Epichrome/Apps and find the folder with the settings for the SSB you're going to recreate. Right click and choose Compress from the drop-down so you know you have a pristine copy of the settings in case anything goes wrong.

Then, basically, the procedure is to *completely* delete the old SSB from the system, meaning either use rm -rf on it, or trash it in the Finder and empty trash. That will make sure is unique identifier is gone from Spotlight. Then if you recreate it with Epichrome using *exactly* the same name (both short and long), it should end up with the same identifier and will automatically use the same settings folder as the old one.

If that doesn't work for some reason, you can look in ~/Library/Application Support/Epichrome/Apps and find the new folder it's created (it will probably look like "Something123"--part of the app name with 3 digits at the end). You can then make sure the new app is *not* running, and then empty that folder out, and replace its contents with the contents of the settings folder from your old SSB.

I hope that's all clear! The procedure is also outlined in the README. Sorry it's not simpler--one of the long-term design goals has been to make editing an SSB possible, but with my work schedule that may be a long way off...

**Comment by ylluminate** [comment] 2016-02-15 16:52
Thanks for the info there.  I'll probably poke around the `.plist` just to see what's going on there.  I'd like to know (at any rate) regarding some settings there.

**Comment by dmarmor** [comment] 2016-02-15 16:59
OK--if you're stout of heart and don't mind editing the Info.plist, then the easiest way to see what you need to do would be to create a dummy SSB with "Register as a browser" turned on. Then in the terminal do a diff on the Info.plist in the dummy SSB and your SSB. The only differences should be in the name fields and the extra keys created in order to register as a browser. You should then be able to just copy those from the dummy's Info.plist to your SSB's Info.plist. Make sure you back up your Info.plist first, as a tiny mistake in that file will render the SSB unable to run. Good luck! Let me know if you have any questions, and also please let me know if and when you get it to work!

**Comment by ylluminate** [comment] 2016-02-15 17:02
Yes, excellent.  That was what I was thinking.  I'm a 20+ year *nix vet so I guess stout of heart is one way to describe me... :D

**Comment by dmarmor** [comment] 2016-02-15 17:26
Great! This should be a cakewalk for you, then.

I just refreshed my memory by looking through my Info.plist filtering code. It looks like the keys you need to add in are:

CFBundleURLTypes
NSPrincipalClass
NSUserActivityTypes

**Comment by dmarmor** [comment] 2016-02-16 05:24
Hmm, so bad news. Not sure if you saw issue #55, but apparently 2.1.10 has broken compatibility with Browser Fairy. I just confirmed it on my system. Looking into it, but I'm not super optimistic about figuring it out quickly. So if you haven't already purchased BF, maybe hold off for now. Sorry for the trouble. Frustrating!

**Comment by dmarmor** [comment] 2016-02-16 06:01
Update: see my latest comment in issue #55 for a partial workaround to the Browser Fairy problem. Unfortunately, more SSB surgery...

**Comment by seanyhc** [comment] 2017-05-07 05:09
I have a related question. I was looking for solutions to this need. I downloaded Choosy (similar to Browser Fairy) and it worked. But because Choosy hasn't been updated for a long time, I switched to BF upon seeing this post. However, I wasn't able to add an app created via Epichrome to its list. I created a GMail app as "browser with tabs". But when I opened BF chrome extension which showed the browser list, I wasn't able to drag GMail into that list. Seems like it wasn't identified as a browser type. Do you know what I should do? Thanks!

**Comment by seanyhc** [comment] 2017-05-07 05:30
After some research I found that my GMail app didn't register as browser. And referencing this thread I was able to find the diff and (I think) made it as a browser. When I choose the list from BF, it showed up as "ChromeEngine.app", with my GMail app icon. Please let me know whether this is the correct behavior. Thanks!
