### ISSUE TITLE
Apps don't load due to "unable to update app to new version of Google  Chrome)

### ISSUE THREAD

**Issue by ljavierrivera** [dmarmor/epichrome#245] opened 2020-06-01 14:11 UTC
On my other laptop still running 10.12.6, I now get the "unable to update app to new version of Google Chrome". 

My Chrome is currently on v83.0.4103 - Should I upgrade to EpiChrome 2.3.2 or are my apps DOA now?

I may have a time machine backup from a couple of weeks back if going that route is an potential solution?

**Comment by dmarmor** [comment] 2020-06-01 21:13
Hi @ljavierrivera, this is a duplicate of #228. This should be fixed in Epichrome 2.3.2, so please install that and try running those apps again. They should now offer to update. If you still have trouble, please post on issue #228. Thanks!

**Comment by dmarmor** [comment] 2020-06-01 21:13
Duplicate of #

**Comment by dmarmor** [comment] 2020-06-01 21:13
Duplicate of #228

**Closed by dmarmor** 2020-06-01 21:13 UTC
