### ISSUE TITLE
SSB App opens default Chrome

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#214] opened 2020-05-13 09:03 UTC
A few time time i had the problem, that suddenly starting a SSB opens my default Chrome. I can't remember the situations exactly, it was during the update of my around 30 SSBs.
But right now it happened again after a Crash ob my Mac.
I solved it by restoring the app folder under /Applications/Epichrome/EpichromeEngines.noindex/<USER>/<APPNAME>/<APPNAME>.app from backup (happy to do backups!).

I kept the broken app if i case i can help debugging.

**Comment by dmarmor** [comment] 2020-05-13 23:03
Hey @talleux, I believe the problem here is with engines getting left in an active state after crashes, and there's no real solution, but an easy workaround to launch each app once from the main app (not the engine) and then quit it gracefully, and that should restore it. There's a more in-depth discussion in issue #202.

**Comment by dmarmor** [comment] 2020-05-13 23:03
Duplicate of #202

**Closed by dmarmor** 2020-05-13 23:03 UTC

**Comment by talleux** [comment] 2020-05-15 08:22
hmmm. i just had the same now (my bloody new MBP 16 like to crash in sleep mode regularly) and starting the app from the /Applications folder didn't help. Even restoring both the folders from /Applications/Epichrome/EpichromeEngines.noindex/<USER>/<APPNAME> and /Users/<USER/Library/Application Support/Epichrome/Apps/<APPNAME> doesn't help. Whichever app i double lick, nothing happens (the windows focus leaves Finder and looks to be nowhere.

How can i recover my app?

I will give it a new chance after restarting my Mac next time i have time for this and report.

**Comment by dmarmor** [comment] 2020-05-15 22:36
Sorry this is still problematic. I'm going to move the conversation over to issue #202, so there's a single place for other folks who run into this to look.
