### ISSUE TITLE
Make it impossible to permanently close the main window

### ISSUE THREAD

**Issue by 75th** [dmarmor/epichrome#266] opened 2020-08-09 02:11 UTC
This is a feature request that can be fulfilled in one of two ways, I don't care which:

1. Make the app quit when you close the main window, or
2. Put an option in the Epichrome Helper extension button to respawn the main window if it's closed.

I don't know if either of these is possible within the limitations of Brave/Chromium or macOS, so feel free to wontfix this if not.

**Comment by dmarmor** [comment] 2020-08-13 23:57
Duplicate of #145 

This is on my to-do list for the next version of the Epichrome extension. That may not happen for a while as I'm in the midst of another relatively major update to the app itself, but once that's out my next priority is to give some TLC to the extension...

**Closed by dmarmor** 2020-08-13 23:57 UTC
