### ISSUE TITLE
Icon set to chrome default regularly while app is running

### ISSUE THREAD

**Issue by talleux** [dmarmor/epichrome#328] opened 2021-04-27 14:21 UTC
I have this issue since about a week now and then for different apps, on a non reproducible way:
*while* an app is running, all of a sudden the icon is set to the chrome default. When i close the app, the icon appears again. Once this happen, i can reproduce this:
- Start the app --> icon set to chrome default. I can see this happen in the finder
- close the app --> App is correct in the finder

Epichrome Scan sees no problem to fix.
Editing the app and setting a new icon helps. Also using a backup version.

Important: i *think* this happens only with icons created *before* Epichrome converts the icon to Big Sur style...

PS: i have no need for this to be fixed, it's more as information in case this can be usefull.
I successively let epichrome recreate the icon of all my apps...

**Comment by dmarmor** [comment] 2021-04-30 16:58
Duplicate of #290 

I'm going to move all discussion of this to that issue. Thanks!

**Closed by dmarmor** 2021-04-30 16:58 UTC
