### ISSUE TITLE
Multiple Apps with same browser broken after reboot

### ISSUE THREAD

**Issue by KajKandler** [dmarmor/epichrome#265] opened 2020-07-27 05:47 UTC
I have multiple Apps, one with Chrome, three with Brave as browser. 

After a reboot (and being asked if I want to re-open the previous tabs), all Epichrome apps start from the Dock only the first App in each group. So the the Chrome apps (Chrome itself and the Epichrome app that uses Chrome) So if I click on the Chrome icon first, also the epichrome app will open a chrome window, not an epichrome customized window.  If I close Chrome, and open the Epichrome app first, all tabs of Chrome will show up as the epichrome app (in the top left menu) and the customization of the epichrome app (set different search engine) is not there. 

The same is true for the the three apps I have based on Brave, When I open BraveA fist, BraveB, BraveC will also open a new window in BraveA, which does not help that much. All this did work just fine before reboot.

Last seen on Epichrome 2.3.4, but previous versions too.

**Comment by dmarmor** [comment] 2020-07-29 22:53
Hi @KajKandler, if I'm understanding what's happening correctly, this probably has to do with an unexpected reboot while apps were running. It's been discussed a lot in issue #202. The solution is outlined in the troubleshooting guide here:

https://github.com/dmarmor/epichrome/blob/master/TROUBLESHOOTING.md#opening-an-app-from-the-dock-opens-a-generic-browser

**Comment by dmarmor** [comment] 2020-07-29 22:53
Duplicate of #202

**Closed by dmarmor** 2020-07-29 22:53 UTC
