### ISSUE TITLE
Sudden incompatibility with BrowserFairy

### ISSUE THREAD

**Issue by rschend** [dmarmor/epichrome#55] opened 2016-02-16 02:12 UTC
First, a big thanks to @dmarmor for the latest update. It sounds like he's busy otherwise, so it was a nice surprise to see the broken icon issue sorted that quickly.

I've been using Epichrome with [BrowserFairy](http://www.browserfairy.com/) to create pretty great workflow, where I force all work-related links to open in my work-specific SSB (the one hooked up to my work Google profile, with all its bookmarks, extensions, etc.). But this has only been possible using the text rules in BF. Even tho BF can direct links based on which app the link is coming from, it can't do it when the app is an Epichrome SSB. The dev says this is because the links are actually coming via a Python script, and not from Chrome itself. He says he plans on adding this functionality soon, which will be great.

In the meantime, it looks like 2.1.10 has broken BF compatibility altogether. Now, when BF tries to direct a link to one of my SSBs, if that SSB isn't already open, then the icon bounces but nothing happens. If it is already open, then a duplicate copy of the icon briefly shows in the dock, then goes away. Either way, I get this console error:

![bf-epi console](https://cloud.githubusercontent.com/assets/10687740/13065175/b453a16e-d427-11e5-900a-c85cf72c6efd.jpg)

'FFD Chrome' is the name of my SSB.

Is this possibly a result of other changes in the new version?

I consider the fact that Epichrome worked with BrowserFairy _at all_ was great, so no complaints here that it might no longer play nice with it. But man, it really could make for an amazing combination.

**Comment by dmarmor** [comment] 2016-02-16 05:22
Well, I've just confirmed this bug on my system (I use Browser Fairy too). No real idea what could be causing it, though. The big change in architecture came in v2.1.8, where I changed over to using a full clone of Chrome as an engine inside each Epichrome app (that was necessary to overcome a problem that was causing Epichrome apps to not properly use the GPU). I would've thought if something was going to break Browser Fairy compatibility, that would've done it. I honestly can't think what I've changed in 2.1.10 that would break things...

Thank you also for letting me know about the text rule situation--good to know the BF dev is aware of us! They're absolutely right, too, links from Epichrome apps are actually coming from a python script, which is the server listening on the other end of the Epichrome Helper extension. This is the only way to route URLs out of Epichrome apps (or out of Chrome itself as far as I know).

If I get a little time here and there, I'll try to poke around and see if I can figure out what's causing the breakage with BF. And if you figure out anything or hear anything from the BF dev, let me know?

**Comment by dmarmor** [comment] 2016-02-16 05:57
I just poked around and have figured out a partial fix. I can get it so that Browser Fairy will work again as long as the SSB is already running. I still can't seem to get it to launch, which makes no sense to me, since if I'm understanding that console log you sent me, it's just trying to launch using /usr/bin/open, which works fine for me via the terminal.

Do you happen to know if Browser Fairy was able to *launch* your SSBs prior to 2.1.10? If not, then it's possible that the architecture change in 2.1.8 broke that, which would at least make some sense to me.

Regardless, that part of the problem I may not be able to fix. I'm having to do some pretty shady stuff to get Chrome to properly run the GPU code, basically spoofing the SSBs so that their main Chrome engine is running under the real Chrome BundleIdentifier. I have a feeling that's what's causing BF to be unable to launch them.

Anyway, it may be a week or more before I have time to do another update. If you're impatient to get BF semi-working again and don't mind doing a little surgery on your SSB, here's what you'd need to do:

Inside your SSB in **Contents/Resources/ChromeEngine.app/Contents/MacOS**, create a file called **Google Chrome**, with the following contents:

```shell
#!/bin/sh
echo
```

Then run the following on it:

```shell
chmod 755 'Google Chrome'
```

Then go back one directory to **Contents/Resources/ChromeEngine.app/Contents** and edit Info.plist. Find the **CFBundleExecutable** key, and change the string below it from **ChromeEngine** to **Google Chrome**.

That's it. After that, as long as the SSB is open, BF should be able to route links to it. I'll add this fix to the next release and keep trying to figure out why it can't launch the SSBs any more.

**Comment by rschend** [comment] 2016-02-16 13:38
Thanks for the quick update.

I could've _sworn_ that it was also successfully launching the SSBs on the previous version. But I've reinstalled 2.1.9 and link direction works again...launching does not. But I've only been using BF for a couple of weeks and it's rare I don't have all my SSBs running at any given time. So you're probably right that launching never worked. And given the way I work, launching is gravy.

I'll try the bandaid fix today. Cheers!

**Comment by dmarmor** [comment] 2016-02-16 15:29
OK, good to hear (at least I don't feel like I'm losing my mind any more). Do let me know how the bandaid works for you, and I'll work on getting it into the next release.

**Comment by rschend** [comment] 2016-02-16 15:47
Bandaid works! Much appreciated.

And I'll be sure to point the BF dev here so he can lend a hand where possible. Having these two apps playing nice is seriously changing the way I get my job done.

Kudos. :+1:

**Comment by rschend** [comment] 2016-02-18 01:27
Would the bandaid fix above also cause the broken icon issue to resurface? 

Just now I created a new SSB with 2.1.10, downloaded a file and the icon stuck. Then I applied the temp fix above, confirmed link direction worked again, and now a file download causes the icon to break. But unlike with 2.1.9, it remains a "broken" icon and doesn't just revert back to the default Chrome icon.
![broken ssb icon](https://cloud.githubusercontent.com/assets/10687740/13130780/b037009c-d5b4-11e5-9ab0-4c0e233543cb.jpg)

So perhaps the issues are directly related after all?

Hope this helps.

**Comment by dmarmor** [comment] 2016-02-18 01:33
Hmm. No, the idea behind changing the CFBundleExecutable key in Info.plist was exactly to avoid that broken icon. Is it possible that there's a typo either in the "Google Chrome" file you created in the MacOS folder or in the string you changed in the Info.plist? Any discrepancy there would cause that broken icon. Or if the Google Chrome file you created isn't executable, that would do it too.

Otherwise, I can't figure out why it'd be giving you that. One way to test it would be to go in the Finder and "Show Package Contents" on your SSB. Navigate to Contents/Resources and look at ChromeEngine.app. If it's showing a "broken" icon in the Finder, then something is wrong...

**Comment by rschend** [comment] 2016-02-18 02:10
Yeah, I'm not sure what's going on. I'm probably just tired. But now, when I just delete all my SSBs (and empty trash) and start over from scratch, it feels like I'm not.

Every time I recreate the SSB, give it the same name and icon, I **do** get the broken icon in the package contents like you mentioned:
![package contents](https://cloud.githubusercontent.com/assets/10687740/13131567/68952e3e-d5ba-11e5-96e5-be81482abb3e.jpg)

This is before applying the fix. All I've done is created the SSB and expanded it.

Also, each time I recreate from scratch, it's already logged me into the same Google profile and all my data is already there. Where is that being stored?

I tried creating a new SSB with a different name and the icon in the contents was not broken. But the app icon did break again upon file download. Doublechecked my work and didn't find any typos.

But again, I'm tired and should probably just wait and try again this weekend.

**Comment by dmarmor** [comment] 2016-02-18 16:37
OK, the only other thing you might try would be just dragging ChromeEngine up to the next level directory  (Contents). I've sometimes had the Finder/Spotlight get confused and not understand that the app bundle is now valid. If you drag it into Contents and the icon changes to the correct icon, then you've made the right changes to the bundle. If you then drag it back, there's a good chance it will remain correct (though in my testing it has also sometimes reverted back to the broken icon.

Anyway, if you play around with that, it might fix it. If not, then likely there's something wrong in the app bundle.

**Comment by jschuster** [comment] 2016-02-18 16:46
Hi Guys, 
I guess the issue with initial starting of the SSB might be an Issue of Browser Fairy. At least it is involved ;)

The problem seems to be a legacy function which was required for Mac OS 10.7 and 10.8.
Omitting that call for Mac OS 10.10 opens the app.

For clarification:
The function tries to open the app before sending the url with a second function call. That was required in older Mac OS versions, it is not required in 10.10 - thus it might be not that perfect fix for all.
The opening fails for "equal" apps like installed Chrome in App Folder and via brew cask - if one instance is already running - trying to open the other instance will fail.
That is reasonable for identical apps in different folders but the SSBs have unique BundleIdentifiers I'm quite confused. 

@dmarmor i think you can concentrate on the issue with the "not opening url while already running".

Please contact me if you want to test a fixed Browser Fairy version.

**Comment by rschend** [comment] 2016-02-20 17:16
Okay, I just had some time this morning to do some more testing.

It's really strange, because I know this worked for me the first time around, but now I'm getting the broken icon issue after applying the BrowserFairy fix no matter how many times I try. Just to be certain, here are the steps I'm taking and the results.

_I decided to re-test just before completing the last step (editing Info.plist), since you said that step was specifically meant to prevent the broken icon issue. But based on my experience, the link routing itself doesn't begin to work until that step is completed, suggesting it's not an additional step to mitigate the icon issue, but rather it's also a critical part of the BrowserFairy fix. Perhaps I misunderstood what you meant there?_

### Create new SSB
* Name: SSB1
* Browser tabs
* Custom Icon

### Test
* BrowserFairy: FAIL (can't route links)
* File download: **PASS** (custom icon sticks) 

### Complete all but last part of fix
* Create file _Google Chrome_
* Move file to **/Users/rfs/Desktop/SSB1.app/Contents/Resources/ChromeEngine.app/Contents/MacOS**
* In Terminal:
```
cd  /Users/rfs/Desktop/SSB1.app/Contents/Resources/ChromeEngine.app/Contents/MacOS
```
```
chmod 755 'Google Chrome`
```
* I see Google Chrome_ become executable

### Test
* BrowserFairy: FAIL
* File download: **PASS** 

### Complete last part of fix
* In **/Users/rfs/Desktop/SSB1.app/Contents/Resources/ChromeEngine.app/Contents/**, open _Info.plist_
* Change:
```
<key>CFBundleExecutable</key>
<string>ChromeEngine</string>
```
to:
```
<key>CFBundleExecutable</key>
<string>Google Chrome</string>
```
### Test
* BrowserFairy: **PASS**
* File download: FAIL

As you can see, as soon as I complete the last step, link routing starts working and custom icons breaks.

Any mistakes in my steps?

**Comment by rschend** [comment] 2016-02-20 17:55
Welp...

To add yet another wrinkle, I'd forgotten that I had successfully performed the fix on another machine. I just checked and link routing and custom icons are working on my existing SSBs there.

But if I try to create a new SSB today and run thru the steps? Same result as above.

And now the strangest part of all....

When I go to inspect the SSB that _works_, i find this in the Info.plist:
```
<key>CFBundleExecutable</key>
<string>Chrome Chrome</string>
```

I didn't even do it right! And yet it works, while following the instructions correctly does not.

I feel like I'm taking crazy pills.

**Comment by dmarmor** [comment] 2016-02-22 02:37
Hey @jschuster! Thanks for checking in. Good to hear that the launch problem may be solvable on your end--I really wasn't sure what I could do about it. I think part of the problem may have to do with the fact that all Epichrome does is wrap instances of Chrome, and the latest engine changes I've made have made that even more explicit. In order to get the SSBs to use the GPU properly, I've had to make the engine a complete clone of Chrome, meaning that when an SSB launches its internal Chrome instance, it's doing so from an app bundle with Chrome's exact CFBundleIdentifier. This is what was causing the icon problem, and also seems to be the root of the Browser Fairy problem.

The solution to getting SSBs to properly accept BF links (at least while already running) seems to be to make the engine look *more* like the real Chrome (go figure), but without knowing more about how BF works, I couldn't figure out any way to get them to launch properly.

Anyway, I'll post when I've got the partial fix uploaded. Meantime, I would love to test the Browser Fairy update so I can try it against my fix. Thanks!

**Comment by dmarmor** [comment] 2016-02-22 02:41
Hey @rschend,

Hmm, so looking at your last couple posts--this may be nothing, but if your chmod command was entered verbatim I think there'd be a problem:

```shell
chmod 755 'Google Chrome`
```

That second quote isn't a quote, but a backtick. Is it possible the file in MacOS isn't named exactly right? Not sure if that'd be responsible for your problem, but it might. Otherwise, it is acting very mysteriously! One thing that's been giving me fits in working on this is that half the time, I get the fix right, but stupid OSX doesn't pick up the changes to the internal app bundle so I can't tell if I've done it right or not.

Anyway, I'm going to put in a couple hours on this tonight, and will try to get an update out (may not happen till later this week, though). Anyway, I'm hoping I can get it working reliably so you won't be stuck trying to kludge it any more!

**Comment by rschend** [comment] 2016-02-22 02:50
Huh, I hadn't even noticed that. But I think that's simply a typo in my post, from when I went back to add some code blocks. I just checked my terminal command history and it's correct there. Plus, if I had gotten it wrong in the terminal, I wouldn't have seen the file turn executable, would I've?

Fiddled around some more today and still can't figure out why I can't make it work again. It's the strangest thing.

Oh, BTW... @jschuster sent me the beta of BF and so far, app launching is working. :+1: 

cheers, -r

**Comment by dmarmor** [comment] 2016-02-22 03:39
Great to hear the beta has app launching working again!

I just uploaded 2.1.11, which *should* fix the link problem for apps already open. Fingers crossed. Give it a shot and let me know how it works for you. Thanks!

I'll optimistically close the issue, but if it's still not right we'll just open it right back up...

**Closed by dmarmor** 2016-02-22 03:39 UTC

**Comment by jschuster** [comment] 2016-02-22 14:12
Hey @dmarmor,
checked it on OS X 10.11 with fixed Browser Fairy. Works like before!
Open in an SSB which is not already running as well as open in an SSB which is already running.

For the beta version can you please contact me via support@browserfairy.com?

**Comment by rschend** [comment] 2016-02-22 14:40
@dmarmor @jschuster 

You guys are awesome. the BF beta and Epichrome 2.1.11 have come together beautifully. Link routing to both closed and open SSBs, as well as custom icons that don't get borked by file downloads...everything is working great now.

So long as I cover all my bases with text rules in BF, it'll be rare that a link gets routed incorrectly. But if you ever do figure out routing based on source SSB, this combination will be about as close to perfect as I could hope for. I've been a loyal paying user of Mailplane for several years. It just got relegated to the dustbin.

And if unread badges ever become a reality, I don't why anyone wouldn't work this way.

Kudos again. Let me know if I can help with further testing.

cheers, -r

**Comment by dmarmor** [comment] 2016-02-23 06:06
Fantastic! Glad it's working well.

Unfortunately, unread badges are not likely anytime soon. I've done some testing, but as far as I can tell there is no way to get them as long as Chrome is the engine. I've had long-term plans for a version of Epichrome that uses Firefox as its underlying engine, and badges would be possible in that case. (But given my work schedule for the foreseeable future, those plans are looking more and more long-term...)
