### ISSUE TITLE
[Needs confirmation] Notifications with actions open in all Epichrome Apps; icons in notifications are not tied to the App that sent it

### ISSUE THREAD

**Issue by webziggy** [dmarmor/epichrome#258] opened 2020-06-24 13:29 UTC
Here's a weird one - I noted that a Google calendar notification, when clicked on, opened the calendar in all of the open Epichrome Apps

I'd created an Epichrome App for GMAIL+GCalendar, and another one for Google Drive, and another for a Confluence Wiki - and when the Google Calendar posted a notification appear in the top right on my mac desktop and I clicked it, it opened Google Calendar in all of the open Epichrome Apps.

Also I noticed that - notifications coming from my Google Drive and Confluence Wiki epichrome apps, had the icon of the Gmail app that I'd created - I think I created that app more recently than the others, so perhaps it's a condition caused by that.

I'm not entirely sure but I think the Google apps I created are using Chrome, and the Wiki one was using Brave... but I'm not entirely sure. I'm also remember something that happened a few days ago so it's possible that it wasn't the Confluence Wiki app that also got Google Calendar opening in it... so maybe it was tied to all Chrome variants. Not sure.

**Comment by webziggy** [comment] 2020-06-24 13:31
May be related to #256

**Comment by dmarmor** [comment] 2020-06-24 22:22
Assuming this is actually only happening on Chrome-based apps, then this is a duplicate of Issue #122. The solution is to use the built-in engine for any apps where notifications are important, as that's the only way apps can have their own unique IDs, which allows the notification system to work properly.

**Comment by dmarmor** [comment] 2020-06-24 22:22
Duplicate of #122

**Closed by dmarmor** 2020-06-24 22:22 UTC
