### ISSUE TITLE
Wrong Epichrome Google Chrome notification icons showing up in notifications 

### ISSUE THREAD

**Issue by ylluminate** [dmarmor/epichrome#122] opened 2017-07-18 03:34 UTC
When certain Epichrome apps issue notifications (ex, Google Docs notifies you of someone making a comment on a document), the icon that shows up on the popup in the upper right of the screen is of another Epichrome app, not of the one that it should be coming from.  For example, if one has an Epichrome instance of Google Docs set up and another Epichrome of GitHub going, when a comment is supposed to be coming in to the Google Docs app the GitHub icon shows up instead on the alert...

**Comment by dmarmor** [comment] 2017-07-19 01:41
Do you have a reliable way of generating one of these notifications? I'd like to be able to see this behavior on my system...

**Comment by ylluminate** [comment] 2017-07-19 03:16
I don't... I am trying it with Google Docs / Drive, but what I thought would generate notifications is not... :\

**Comment by ylluminate** [comment] 2017-07-19 03:25
So I managed to see a notification, but it was indeed still from another Epichrome app.  Now, one thing to note, this is not necessarily new I don't think.  I didn't use notifications until recently and I believe that it exhibited this problem prior to the .17 update...  But I cannot be sure.

**Comment by dmarmor** [comment] 2017-07-19 03:49
Hmm. OK, yeah, I'd have guessed that if this was introduced in .18, the .19 rollback would've fixed it. I have a Google Drive app myself, so I'll try to figure out how to make it send me a notification and test it out a bit. It's possible that this is just an inevitable side effect of the fact that all these Epichrome apps are just instances of Chrome, so the Chrome notification system might get confused by them.

**Comment by KajKandler** [comment] 2019-02-12 12:34
This still persists EpiChrome 2.2.3, OS Mojave latest, Chrome Version 71.0.3578.98 , It seems to me that it always takes the latest Apps icon. As a matter of fact it even changes the icon of an existing notification, when I switch to a different EpiChrome browser while it is displayed.

To reproduce, create an epichrome for GMail and send your self an email. Or create one for google calendar and create events with notifications (you can have many in a 1 min interval)

**Comment by dmarmor** [comment] 2019-03-19 23:57
Hey all, adding in @dsemaya and @talleux who commented in #128 that this notification problem also causes the wrong app to be brought forward when a notification is clicked.

Just a heads-up, this may not be a solvable problem. I am not able to give the Chrome instances run by Epichrome apps unique bundle IDs, because any changes to the codesigned resources in Chrome causes it to not run properly. I will check and see if there's some nested icon file that I can override to solve the icon problem. It seems unlikely I'll be able to solve the other issue where the wrong app is brought forward.

**Comment by dmarmor** [comment] 2019-09-21 00:22
Just an update this is still on my radar and I will look into it.

**Comment by dmarmor** [comment] 2019-12-02 22:52
Hi all,

I'm working on a major update that I believe will solve this issue (as well as many other long-standing problems). With my work schedule, it may take a while, but I'll let you know when it's ready for testing. Thanks for your patience!

One more thing:

#### <shameless_plug>
#### I've set up a [Patreon](https://www.patreon.com/epichrome). If you find Epichrome useful and would like to help support its continued development, I've love it if you considered joining. Your membership would help cover the costs and time I put into the project. Membership is per-release, so you'd only be charged when I put out a new version with significant work in it.
#### </shameless_plug>

**Comment by dmarmor** [comment] 2020-05-13 00:40
Hi all!This issue should be solved in 2.3.0. If you're using the external Chrome engine (which is probably the case for any apps you update) you will probably still experience getting the default Chrome icon on your notifications, so for apps that use notifications I highly recommend creating new apps using the built-in Brave engine (or using the advanced procedure outlined in the installer package Readme to switch engines on update). Apps with the built-in engine will always show their own icon on notifications.

Closing the issue for now. If you notice this problem in the latest update, please let me know and I'll reopen.

**Closed by dmarmor** 2020-05-13 00:40 UTC
Labels: pending
