### ISSUE TITLE
Regular Chrome can't be default browser after update to macOS 10.12.5

### ISSUE THREAD

**Issue by jarredt** [dmarmor/epichrome#116] opened 2017-05-24 16:41 UTC
Just updated to macOS 10.12.5, and now Chrome cannot be set as my default browser. Options listed are Safari, "ChromeEngine.app" (which has the icon of my single Epichrome app), and iTerm. Tried to set as default from Chrome itself, but it doesn't work.

If I delete the Epichrome app, then the "ChromeEnginer.app" option disappears and Chrome can be set to default browser.

(Note: I was able to force Epichrome to open my Epichrome app  links in Chrome through the fix [here](https://github.com/dmarmor/epichrome/issues/114), but that doesn't solve the system-wide default browser problem.

**Comment by dpickett** [comment] 2017-06-01 15:10
:+1: I am also having this issue.

**Comment by henderea** [comment] 2017-06-01 15:17
I've been having this issue too.

**Comment by wizonesolutions** [comment] 2017-06-05 14:23
Workaround found! First, run the script in the other issue. Then, when you try to make Chrome your default browser and it asks you if you want to keep [default browser] or change to [name of random Epichrome app], click on the name of the Epichrome app. This actually opens links in Chrome, even if you have the Epichrome app open.

So it's some weird naming issue, not a functionality issue.

**Comment by henderea** [comment] 2017-06-05 14:46
I will say, however, that BrowserFairy doesn't seem to recognize Chrome in the cmd-click popup.  This causes problems for me when I cmd-click a link in iTerm2, since it only offers Safari and Firefox.  So even if it *is* just a naming issue, if there is anything that depends on that name, it will have problems.

**Comment by whatknows** [comment] 2017-06-13 14:43
👍

**Comment by henderea** [comment] 2017-06-13 20:10
@whatknows the issue you're seeing is actually #114, not this one.  There is info on fixes in that issue.

**Comment by dmarmor** [comment] 2017-07-15 21:21
Hey all, I think I've got a fix for this in 2.1.17 which I'm working on a release for today. It also fixes #114. Stay tuned...

**Closed by dmarmor** 2017-07-15 21:21 UTC

**Comment by Matts966** [comment] 2018-10-04 05:36
Hi, is this problem reproduced now?
I'm using MacOS Mojave and can't select chrome as default browser, and select an epichrome app.

Thank you.

**Comment by heyfletch** [comment] 2018-10-09 13:04
I've opened an issue here #169
