### ISSUE TITLE
macOS big sur

### ISSUE THREAD

**Issue by infira** [dmarmor/epichrome#280] opened 2020-11-14 10:19 UTC
After upgrade to bigSur epic chrome stoped working.
I had this error in log
"*[10940]Gmail062(739)/clearmasterprefs(2481): Timed out waiting for app prefs to appear.
![10940]Gmail062(860)/abort(884): Aborting: The app may not have launched properly. If it did, the engine will not be properly cleaned up upon quitting.
"
Tried to clean remove with App cleaner "https://freemacsoft.net/appcleaner/" and reinstall in still same error

**Comment by barak-haviv** [comment] 2020-11-15 10:05
Have the same problem

**Comment by dmarmor** [comment] 2020-11-15 17:25
Duplicate of #275

**Closed by dmarmor** 2020-11-15 17:25 UTC
