### ISSUE TITLE
Lost App icon and App name when upgrading to 2.3.24

### ISSUE THREAD

**Issue by asmod3us** [dmarmor/epichrome#295] opened 2021-02-02 08:25 UTC
One of my apps lost its app icon in dock and app switcher as well as its name and is now just showing as generic Google Chrome. What details can I provide to troubleshoot?

**Comment by talleux** [comment] 2021-02-05 11:22
See #290 + #226, maybe is this the same issue?

**Comment by dmarmor** [comment] 2021-02-07 18:59
Hi @asmod3us, depending how you set your custom icon, this is probably either #226 or #290. Could you please see my latest comment at the end of #226, and then if it looks like #290, let me know some more details about how and when it's happening in that issue's comments (e.g. what OS version, which engine the app uses, etc.).

Thanks @talleux for helping sort all this out!

Duplicate of #290

**Closed by dmarmor** 2021-02-07 18:59 UTC
