### ISSUE TITLE
can't run 2 Epichrome apps at the same time.  BigSur

### ISSUE THREAD

**Issue by alatteri** [dmarmor/epichrome#281] opened 2020-11-17 22:43 UTC
just upgraded to BigSur.  I am unable to have 2 Epichrome apps run at the same time, although any singularly runs fine.  See attached screen record.
[Screen Recording 2020-11-17 at 2.39.51 PM.mp4.zip](https://github.com/dmarmor/epichrome/files/5556640/Screen.Recording.2020-11-17.at.2.39.51.PM.mp4.zip)

**Comment by dmarmor** [comment] 2020-11-20 01:51
Duplicate of #275

**Closed by dmarmor** 2020-11-20 01:51 UTC
