### ISSUE TITLE
App aborted with error: "Error launching engine: The application “Keystone Academy.app” could not be launched because a miscellaneous error occurred. The app may not have launched properly. If it did, the engine will not be properly cleaned up upon quitting." [main(665)]

### ISSUE THREAD

**Issue by woodchen** [dmarmor/epichrome#318] opened 2021-04-12 01:15 UTC
```
*[614]KeystoneA536(545)/launchapp(2887): Error launching engine: The application ‚ÄúKeystone Academy.app‚Äù could not be launched because a miscellaneous error occurred.
![614]KeystoneA536(665)/abortreport(1155)/abort(1093): Aborting: Error launching engine: The application ‚ÄúKeystone Academy.app‚Äù could not be launched because a miscellaneous error occurred. The app may not have launched properly. If it did, the engine will not be properly cleaned up upon quitting.

```

**Comment by dmarmor** [comment] 2021-04-17 22:29
Duplicate of # 317

**Closed by dmarmor** 2021-04-17 22:29 UTC
