### ISSUE TITLE
Version 2.4.6 app aborted with error: "Error launching engine: After 2 attempts: The application “Habitica Chrome.app” could not be launched because it is corrupt. The app may not have launched properly. If it did, the engine will not be properly cleaned up upon quitting." [main(678)]

### ISSUE THREAD

**Issue by icotext** [dmarmor/epichrome#337] opened 2021-05-12 09:44 UTC
```
*[11435]HabiticaC540(547)/launchapp(2902): Error launching engine: After 2 attempts: The application ‚ÄúHabitica Chrome.app‚Äù could not be launched because it is corrupt.
![11435]HabiticaC540(678)/abortreport(1155)/abort(1093): Aborting: Error launching engine: After 2 attempts: The application ‚ÄúHabitica Chrome.app‚Äù could not be launched because it is corrupt. The app may not have launched properly. If it did, the engine will not be properly cleaned up upon quitting.

```

**Comment by dmarmor** [comment] 2021-05-12 16:43
Duplicate of #307

**Closed by dmarmor** 2021-05-12 16:43 UTC
