### ISSUE TITLE
Desktop (Spaces) Assignments Don't Stick

### ISSUE THREAD

**Issue by robmathers** [dmarmor/epichrome#65] opened 2016-04-27 02:27 UTC
I'm finding that assigning an Epichrome created app to a particular desktop (aka spaces) isn't working as it should. When you initially assign it to a desktop (left click the icon in the dock, *Options > Assign To*), it functions as expected, but on further launches, it will open in the current desktop.

If assigned to all desktops, it only shows in the initial one, until reassigned. If assigned to a particular desktop, it will open in the currently open desktop, but OS X will switch to the desktop it should be in (without the app moving).

This is in OS X 10.10.5. I haven't tested in 10.11.

**Comment by cmacminn** [comment] 2016-06-08 22:48
I agree --- Still a problem in 10.11.5.

**Comment by dmarmor** [comment] 2016-06-13 01:41
I did a little experimentation, and I think the problem is unsolvable and has to do with the nature of Epichrome. All Epichrome is is a wrapper around an instance of Chrome. So when you launch an Epichrome app, it properly sends it to the correct desktop--but then the app launches Chrome, which is assigned to whatever desktop it's assigned to, and that's where the final "app" you interact with will open.

To confirm this behavior, I tried changing the Assign To for Chrome itself, and found that my Epichrome apps launched in whatever desktop I'd assigned Chrome to.

Sorry I can't support this, but I think it's literally impossible since all we're really doing is launching instances of Chrome.

**Closed by dmarmor** 2016-06-13 01:41 UTC

**Comment by cmacminn** [comment] 2016-06-14 14:03
Thanks very much for the update on this. I understand your point, but I was
previously using an app called Fluid for making Safari-based SSBs and it
did not have this problem?

**Comment by breeden** [comment] 2016-06-14 19:23
I believe Fluid uses WebKit for rendering web pages. So, when you assign a Fluid app to a desktop, it will stay put just fine. As @dmarmor was saying, Epichrome is just a wrapper for Chrome, so it doesn't draw its own windows directly -- Chrome does. That means Epichrome windows will always appear in whatever desktop Chrome is assigned to, and there's no way around it within the current framework.

**Comment by cmacminn** [comment] 2016-06-19 08:57
Epichrome windows do respect individual Spaces assignments, but they lose
them upon quitting and relaunching. They can be fixed after relaunch by
changing the setting to something else and then changing it back to the
desired setting. Is it possible to have the wrapper reinforce the correct
Spaces assignment each time it is launched? (Can an application change its
own Spaces setting?)

**Comment by dmarmor** [comment] 2016-06-19 14:32
As far as I know, there isn't a way for an application to adjust its Spaces settings. Even if they were, I doubt I could do it in Epichrome, because all Epichrome does ultimately is spawn a special instance of Chrome. When the Epichrome wrapper opens it already is obeying its Spaces setting, but the Chrome instance it launches obeys Chrome's settings.

So for now, I don't think there's any way I can fix this. The best (though imperfect) solution might be to use something like this recipe in Keyboard Maestro (which is a paid product but well worth it in my opinion--I use it heavily):

https://forum.keyboardmaestro.com/t/move-window-1-space-left-right-or-to-different-desktop/3100

**Comment by msubel** [comment] 2017-10-03 06:41
I think I may have found a workaround for this issue. My tests on 10.12.6 show that assigning the main Chrome app to no particular space (right-click dock icon -> Options -> Assign to: None) allows Epichrome apps to respect their desktop assignment. Of course you need to remember to launch the main Chrome app from the correct space or move it, but I think it's better to do it with one app than potentially with many (Epichrome apps)

**Comment by cmacminn** [comment] 2017-10-03 12:24
What I ultimately want is for my Epichrome apps (Gmail and Google Calendar)
to appear in *all* spaces. Along the lines of your suggestion, it seems
like my desired result can be achieved by assigning Chrome itself to "All
spaces". This works fine as long as one doesn't want to use Chrome as a web
browser for other purposes, since the windows will of course appear in all
spaces.
