### ISSUE TITLE
Default Browser Changes to Epichrome App

### ISSUE THREAD

**Issue by heyfletch** [dmarmor/epichrome#169] opened 2018-10-09 12:59 UTC
Whenever I launch an Epichrome app, the macOS Default Browser changes to that app. It removes Google Chrome as a browser option in System Preferences > General > Default web browser. I have uninstalled/reinstalled both Epichrome (2.2.3) and Chrome (69) on Mojave. 

If I have registered the Epichrome app as a browser, then System Preferences lists 2 of those browsers (i.e., 2 "DevBrowsers"). If I do not register the app as a browser, then the Default web browser changes to that app, e.g., "Gmail", and removes Google Chrome as an option. 

Opening a 3rd app, e.g., "Asana", then switches the Default browser to "Asana". 

In Epichrome Options, there are 2 choices: Default browser and This app. Curious if one possible solution would be to change that option screen to list set browsers so I can "hard code" it to be Google Chrome. 

![2018-10-09_08-59-26](https://user-images.githubusercontent.com/658245/46671171-19099900-cba2-11e8-91cd-5e15428b7a8d.png)
![2018-10-09_09-01-05](https://user-images.githubusercontent.com/658245/46671180-1c9d2000-cba2-11e8-80a8-bbeb61206c33.png)

**Comment by anbie** [comment] 2018-11-12 11:34
I also see this issue on my Mac running macOS 10.14.1 and Chrome 70.0.3538.77 and Epichrome. It's quite annoying since Chrome is my most used browser and I'm using Epichrome to give web-based mail and calendar apps their own app appearance. With not being able to select proper Chrome as the macOS default browser this creates quite some mess with different instances of Chrome and Epichrome when opening links.

**Comment by garhbod** [comment] 2018-12-17 01:36
Work around could be create another epichrome app and select browser in the steps. At the first run don't enable the epichrome extension and you have essentially created a chrome alias. Then make it your default browser.

**Comment by matteopalama** [comment] 2018-12-18 08:03
Hi

You mean “register as a browser” during the setup?. I tried that and now i have an Epichrome available as a default browser, but not my Chrome installation

**Comment by heyfletch** [comment] 2018-12-19 20:23
The problem is that the default browser keeps changing mysteriously, most likely when I switch to other epichrome apps, somehow the macOS switches that to the default browser. This whole issue has made it unbearable to use separate Epichrome apps, so I have given up until this gets sorted out.

**Comment by philc** [comment] 2019-02-25 23:04
This issue is pretty crippling. I've been using epichrome for years but today had to stop using it. I've switched back to using multiple first-class browsers for work gmail, calendar, and personal gmail (chrome, firefox, chrome canary) which is more painful but sufficient.

**Comment by dmarmor** [comment] 2019-02-27 01:18
I've just done a beta update to try to solve some of these default browser problems. I'd appreciate if people who are experiencing this problem could give it a try and let me know if it helps. You'll find the link below.

Note: I suspect you will still see the cosmetic problem that if Chrome is your default browser, the System Preferences pane will show a random running Epichrome app. This is pretty much unavoidable, as running Epichrome apps are just instances of Chrome. But you should see that if you quit all Epichrome apps, then the System Preferences pane should go back to correctly showing Chrome.

More importantly, even when it's showing the wrong running app, Chrome should still be the default, and this update should cause it to work properly as such--at least for links that are redirected using the Epichrome extension. If you're trying to double-click links from the desktop and such, then I can't help with that, as the OS will very possibly still route them erratically.

If that's a common situation for you, I highly recommend spending a couple bucks on [Browser Fairy](https://itunes.apple.com/us/app/browser-fairy/id483014855?mt=12). I use it as my default browser. It works extremely well with Epichrome apps, and also works perfectly for routing links to Chrome regardless of source or how many Epichrome apps I have open.

Anyway, here's the beta. Thanks for your help!

[epichrome-2.2.4b01.dmg.zip](https://github.com/dmarmor/epichrome/files/2908136/epichrome-2.2.4b01.dmg.zip)

**Comment by garhbod** [comment] 2019-03-05 23:50
For those wanting links to open in the base instance of chrome I found https://will-stone.github.io/browserosaurus/

**Comment by dmarmor** [comment] 2019-03-09 00:05
Closing this issue--I believe this behavior is caused by the same problem as Issue #163.

**Closed by dmarmor** 2019-03-09 00:05 UTC

**Comment by heyfletch** [comment] 2019-03-25 22:02
Thanks for the fix. The latest update has fixed this issue for me.
